export const DISTANCE_IN_METERS_AVERAGE = 6900;

export const ELEVATION_IN_METERS_AVERAGE = 83;

export const DURATION_PER_ELEVATION_AVERAGE = 109;

export const BEATS_PER_MINUTE_AVERAGE = 133;

export const SPEED_IN_METERS_PER_SECOND_AVERAGE = 3;

export const PACE_IN_MINUTES_PER_KILOMETER_AVERAGE = 8.72;

export const STEPS_AVERAGE = 6671;

export const DURATION_IN_SECONDS = 2542;
