export const DISTANCE_IN_METERS_AVERAGE = 8574;

export const ELEVATION_IN_METERS_AVERAGE = 107;

export const ELEVATION_AND_DISTANCE_PEARSON_PROJECT = 0.517794064;

export const BEATS_PER_MINUTE_AVERAGE = 147;

export const SPEED_IN_METERS_PER_SECOND_AVERAGE = 2.815;

export const PACE_IN_MINUTES_PER_KILOMETER_AVERAGE = 6.556;

export const STEPS_AVERAGE = 8335;

export const DURATION_IN_SECONDS = 3152;
